# Generated by Django 4.0.6 on 2022-07-09 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de producto')),
                ('nombreProducto', models.CharField(max_length=80, verbose_name='Nombre del producto')),
                ('categoria', models.CharField(max_length=80, verbose_name='Nombre Categoría')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción del producto')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('porcSub', models.IntegerField(verbose_name='Descuento Subscriptor')),
                ('porcOferta', models.IntegerField(verbose_name='Descuento Oferta')),
                ('imagenProducto', models.CharField(max_length=300, verbose_name='Imágen Producto')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=80, null=True, verbose_name='Rut')),
                ('direccion', models.CharField(blank=True, max_length=80, null=True, verbose_name='Dirección')),
                ('imagenUs', models.CharField(blank=True, max_length=300, null=True, verbose_name='Imágen Usuario')),
                ('esSubscriptor', models.CharField(blank=True, max_length=2, null=True, verbose_name='Es Suscriptor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idc', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id carro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Tienda.perfilusuario')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Tienda.producto')),
            ],
        ),
    ]
