# Generated by Django 4.0.6 on 2022-07-09 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('idBoleta', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Compra')),
                ('monto', models.IntegerField(verbose_name='Total pagado')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('estadoActual', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado actual')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Tienda.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('idd', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id detalle')),
                ('porcSub', models.IntegerField(verbose_name='Descuento Subscriptor')),
                ('porcOferta', models.IntegerField(verbose_name='Descuento Oferta')),
                ('subTotal', models.IntegerField(verbose_name='subTotal')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('idBole', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Tienda.boleta')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Tienda.producto')),
            ],
        ),
    ]
