# Generated by Django 4.0.6 on 2022-07-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_producto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
